import { openDatabaseSync } from "expo-sqlite";
import { drizzle } from "drizzle-orm/expo-sqlite";
import { migrate } from "drizzle-orm/expo-sqlite/migrator";
import migrations from "./migrations/migrations.js"; // generated by drizzle-kit

const sqlite = openDatabaseSync("timemapper.db");
// SQLite leaves FK enforcement off by default per-connection. We rely on
// ON DELETE CASCADE for place hard-deletes (see 0002_cascade migration),
// so enable it immediately after the handle opens — before any reads or
// writes touch the schema.
sqlite.execSync("PRAGMA foreign_keys = ON;");
export const db = drizzle(sqlite);

export async function runMigrations() {
  await migrate(db, migrations);
}
