import { openDatabaseSync } from "expo-sqlite";
import { drizzle } from "drizzle-orm/expo-sqlite";
import { migrate } from "drizzle-orm/expo-sqlite/migrator";
import migrations from "./migrations/migrations.js"; // generated by drizzle-kit

const sqlite = openDatabaseSync("timemapper.db");
export const db = drizzle(sqlite);

export async function runMigrations() {
  await migrate(db, migrations);
}
